# Generated by Django 3.2.8 on 2021-11-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thongtin',
            fields=[
                ('idthongtin', models.AutoField(primary_key=True, serialize=False)),
                ('tieude', models.CharField(max_length=100, verbose_name='Tiêu đề')),
                ('nguoidang', models.CharField(max_length=100, verbose_name='Người đăng')),
                ('hinh', models.ImageField(upload_to='', verbose_name='Hình ảnh')),
            ],
        ),
    ]
