# Generated by Django 3.2.8 on 2021-11-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sanpham',
            fields=[
                ('masp', models.AutoField(primary_key=True, serialize=False)),
                ('tensp', models.CharField(max_length=100, verbose_name='Tên sản phẩm')),
                ('giaban', models.IntegerField(max_length=100, verbose_name='Giá bán')),
                ('hinhsanpham', models.ImageField(upload_to='', verbose_name='Hình SP')),
                ('noidungsp', models.CharField(max_length=100, verbose_name='Nội dung sản phẩm')),
                ('donvitinh', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('lít', 'lít'), ('chai', 'chai')], max_length=50, verbose_name='Đơn vị tính')),
                ('soluong', models.IntegerField(max_length=50, verbose_name='Số lượng')),
            ],
        ),
    ]
