# Generated by Django 3.2.8 on 2021-11-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211117_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtin',
            name='noidungthongtin',
            field=models.TextField(max_length=3000, null=True, verbose_name='Nội dung bài'),
        ),
    ]
