# Generated by Django 4.0 on 2021-12-14 04:21

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_thongtin_noidungthongtin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimKiemAnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.timkiemanh_img_path)),
            ],
        ),
    ]
