# Generated by Django 4.0 on 2021-12-29 02:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0005_thongtindathang'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatHang1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinhdathang', models.ImageField(upload_to='')),
                ('soluongdathang', models.CharField(max_length=10)),
                ('giadathang', models.IntegerField()),
                ('tendathang', models.CharField(max_length=100)),
                ('maildathang', models.EmailField(max_length=100)),
                ('diachidathang', models.TextField(max_length=500)),
                ('sdtdathang', models.CharField(max_length=20)),
                ('ngaydathang', models.DateField(default=datetime.datetime.today)),
                ('sanphamdathang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sanpham')),
                ('usedathang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
