# Generated by Django 4.0 on 2021-12-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_dathang1_qhuyendh_dathang1_thanhphodh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanpham',
            old_name='hinhsanpham',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='sanpham',
            old_name='tensp',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sanpham',
            old_name='giaban',
            new_name='price',
        ),
    ]
