# Generated by Django 4.0 on 2021-12-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_hinhsanpham_sanpham_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dathang1',
            name='sanphamdathang',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
