# Generated by Django 4.0 on 2021-12-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_dathang1_qhuyendh_alter_dathang1_thanhphodh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dathang1',
            name='tongtien',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
