# Generated by Django 4.0 on 2021-12-31 01:51

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_dathang1_tongtien'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongtin',
            name='ngaydangbai',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='thongtin',
            name='noidungthongtin',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
