# Generated by Django 4.0 on 2022-01-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_dathang1_trangthaidathang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='noidungsp',
            field=models.TextField(default='', verbose_name='Nội dung sản phẩm'),
        ),
    ]
